name: Beta Deploy
on:
  push:
    branches:
      - release
      - citest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: |
          npm i -g yarn
          yarn install
          yarn release
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -am "Release"
          git push
          